name: initial_intent
description: Reads data from start intent or launch url
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.toolstation.flutter.plugins.initial_intent
        pluginClass: InitialIntentPlugin
      ios:
        pluginClass: InitialIntentPlugin
    